"""migration

Revision ID: 090986f2d719
Revises: ea7b014742e2
Create Date: 2024-02-12 15:06:27.610647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090986f2d719'
down_revision = 'ea7b014742e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.add_column(sa.Column('male_clothing_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('women_clothing_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('fitnes_thing_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitnes_thing_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('women_clothing_type')
        batch_op.drop_column('male_clothing_type')

    # ### end Alembic commands ###
