"""migration

Revision ID: 3af52b43cc98
Revises: 71001f3c7e31
Create Date: 2024-02-10 13:33:33.723251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af52b43cc98'
down_revision = '71001f3c7e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('subcategory_type', sa.String(length=15), nullable=True))
        batch_op.alter_column('delivery_action',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.alter_column('delivery_action',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
        batch_op.drop_column('subcategory_type')
        batch_op.drop_column('category_type')

    # ### end Alembic commands ###
