"""migration

Revision ID: 71001f3c7e31
Revises: a76e7052def4
Create Date: 2024-02-09 22:46:28.042962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71001f3c7e31'
down_revision = 'a76e7052def4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo1', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('photo2', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('photo3', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.drop_column('photo3')
        batch_op.drop_column('photo2')
        batch_op.drop_column('photo1')

    # ### end Alembic commands ###
