"""migration

Revision ID: ea7b014742e2
Revises: 3af52b43cc98
Create Date: 2024-02-11 13:13:19.369566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7b014742e2'
down_revision = '3af52b43cc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saves', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_add', schema=None) as batch_op:
        batch_op.drop_column('saves')

    # ### end Alembic commands ###
